version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: buntzen_sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PHSA_SC_Perf_2026!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
